In [2]:
import pandas as pd

from app.services.csv_reader import read_openrocket_csv
from app.services.data_extractor import extract_useful_columns
from app.services.data_normalizer import normalize_openrocket_data

In [3]:
fichier = "sample_data/open_rocket_data2++.csv"

df_raw = read_openrocket_csv(fichier)

In [4]:

df_raw.columns.tolist()

['Temps (s)',
 'Altitude (m)',
 'Altitude above sea level (m)',
 'Vitesse verticale (m/s)',
 'Vitesse totale (m/s)',
 'Accélération verticale (m/s²)',
 'Accélération totale (m/s²)',
 "Position à l'est du lancement (m)",
 'Position au nord du lancement (m)',
 'Distance latérale (m)',
 'Direction latérale (°)',
 'Vitesse latérale (m/s)',
 'Accélération latérale (m/s²)',
 'Latitude (° N)',
 'Longitude (° E)',
 "Angle d'attaque (°)",
 'Taux de roulis (°/s)',
 'Taux de tangage (°/s)',
 "Taux d'embardée (°/s)",
 'Orientation verticale (zénith) (°)',
 'Orientation latérale (azimut) (°)',
 'Masse (g)',
 'Masse du propergol (g)',
 "Moment d'inertie longitudinale (kg·m²)",
 "Moment d'inertie rotatif (kg·m²)",
 'Accélération Gravitationnelle (m/s²)',
 'Emplacement du CP (cm)',
 'Emplacement du CG (cm)',
 'Calibres marge de stabilité (\u200b)',
 'Poussée (N)',
 'Thrust-to-weight ratio (\u200b)',
 'Force de traînée (N)',
 'Coefficient de traînée (\u200b)',
 'Coefficient de traînée de friction (\u200b)',
 'Coefficient de traînée de pression (\u200b)',
 'Coefficient de traînée de base (\u200b)',
 'Coefficient de trainée axiale (\u200b)',
 'Coefficient de force normale (\u200b)',
 'Coefficient de moment de tangage (\u200b)',
 "Coefficient de moment d'embardée  (\u200b)",
 'Coefficient de force latérale  (\u200b)',
 'Coefficient de moment de roulis  (\u200b)',
 'Coefficient de forçage de roulis (\u200b)',
 "Coefficient d'amortissement de roulis (\u200b)",
 "Coefficient d'amortissement de tangage (\u200b)",
 'Vitesse de vent (m/s)',
 'Wind direction (°)',
 "Température de l'air (°C)",
 'Pression atmosphérique (mbar)',
 'Air density (g/cm³)',
 'Vitesse du son (m/s)',
 'Mach number (\u200b)',
 'Nombre de Reynolds (\u200b)',
 'Longueur de référence (cm)',
 'Surface de référence (cm²)',
 'Pas de simulation du temps (s)',
 'Temps de calcul (s)',
 'Accélération de Coriolis (m/s²)']

In [6]:
df_raw

,Temps (s),Altitude (m),Altitude above sea level (m),Vitesse verticale (m/s),Vitesse totale (m/s),Accélération verticale (m/s²),Accélération totale (m/s²),Position à l'est du lancement (m),Position au nord du lancement (m),Distance latérale (m),...,Pression atmosphérique (mbar),Air density (g/cm³),Vitesse du son (m/s),Mach number (​),Nombre de Reynolds (​),Longueur de référence (cm),Surface de référence (cm²),Pas de simulation du temps (s),Temps de calcul (s),Accélération de Coriolis (m/s²)
0,0.000,0.000000,0.000000,0.000,0.000,0.000000,0.000,0.000000,0.000,0.000000,...,1013.250,0.001,340.389,0.006,388300.0,15,176.715,0.010,0.036,0.000000
1,0.010,0.000000,0.000000,0.007,0.010,4.316000,5.727,0.000000,0.000,0.000000,...,1013.250,0.001,340.389,0.006,393300.0,15,176.715,0.010,0.044,0.000001
2,0.020,0.000523,0.000523,0.121,0.136,18.426000,19.910,0.000314,0.000,0.000314,...,1013.250,0.001,340.389,0.006,408600.0,15,176.715,0.010,0.047,0.000018
3,0.030,0.003000,0.003000,0.376,0.407,32.541000,34.455,0.001000,0.000,0.001000,...,1013.250,0.001,340.389,0.007,436100.0,15,176.715,0.010,0.049,0.000053
4,0.040,0.009000,0.009000,0.772,0.824,46.661000,49.044,0.004000,0.000,0.004000,...,1013.249,0.001,340.389,0.007,482900.0,15,176.715,0.010,0.051,0.000107
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3370,785.238,7.004000,7.004000,-4.847,5.361,0.008000,0.365,1155.828000,2.086,1155.830000,...,1012.429,0.001,340.361,0.014,937400.0,15,176.715,0.247,0.812,0.000705
3371,785.486,5.805000,5.805000,-4.846,5.398,-0.000045,0.334,1155.250000,2.086,1155.252000,...,1012.569,0.001,340.366,0.014,937000.0,15,176.715,0.500,0.812,0.000711
3372,785.986,3.382000,3.382000,-4.846,5.327,-0.003000,0.058,1154.102000,2.085,1154.104000,...,1012.853,0.001,340.376,0.014,936600.0,15,176.715,0.248,0.812,0.000699
3373,786.233,2.183000,2.183000,-4.846,5.321,0.005000,0.267,1153.557000,2.085,1153.559000,...,1012.994,0.001,340.380,0.014,937200.0,15,176.715,0.450,0.812,0.000698
3374,786.684,0.000000,0.000000,-4.844,5.271,-0.005000,0.007,1152.594000,2.085,1152.596000,...,1013.250,0.001,340.389,0.014,936600.0,15,176.715,NaN,0.812,0.000690

In [7]:
df_useful = extract_useful_columns(df_raw)

df_useful.head()

,Temps (s),Altitude (m),Vitesse totale (m/s),Masse (g),Emplacement du CP (cm),Emplacement du CG (cm),Calibres marge de stabilité (​),Coefficient de force normale (​),Température de l'air (°C),Pression atmosphérique (mbar),Air density (g/cm³),Mach number (​)
0,0.00,0.000000,0.000,23670.0,NaN,199.924,NaN,NaN,15.0,1013.250,0.001,0.006
1,0.01,0.000000,0.010,23670.0,NaN,199.921,NaN,NaN,15.0,1013.250,0.001,0.006
2,0.02,0.000523,0.136,23660.0,NaN,199.917,NaN,NaN,15.0,1013.250,0.001,0.006
3,0.03,0.003000,0.407,23660.0,NaN,199.914,NaN,NaN,15.0,1013.250,0.001,0.007
4,0.04,0.009000,0.824,23660.0,NaN,199.911,NaN,NaN,15.0,1013.249,0.001,0.007

In [8]:
df_clean = normalize_openrocket_data(df_useful)

df_clean.head(20)

,Temps (s),Altitude (m),Vitesse totale (m/s),Masse (g),Emplacement du CP (cm),Emplacement du CG (cm),Calibres marge de stabilité (​),Coefficient de force normale (​),Température de l'air (°C),Pression atmosphérique (mbar),Air density (g/cm³),Mach number (​)
0,0.00,0.000000,0.000,23670.0,NaN,199.924,NaN,NaN,15.000,1013.250,0.001,0.006
1,0.01,0.000000,0.010,23670.0,NaN,199.921,NaN,NaN,15.000,1013.250,0.001,0.006
2,0.02,0.000523,0.136,23660.0,NaN,199.917,NaN,NaN,15.000,1013.250,0.001,0.006
3,0.03,0.003000,0.407,23660.0,NaN,199.914,NaN,NaN,15.000,1013.250,0.001,0.007
4,0.04,0.009000,0.824,23660.0,NaN,199.911,NaN,NaN,15.000,1013.249,0.001,0.007
5,0.05,0.019000,1.331,23650.0,NaN,199.903,NaN,NaN,15.000,1013.248,0.001,0.008
6,0.06,0.034000,1.872,23640.0,NaN,199.895,NaN,NaN,15.000,1013.246,0.001,0.010
7,0.07,0.054000,2.445,23630.0,NaN,199.887,NaN,NaN,15.000,1013.244,0.001,0.011
8,0.08,0.080000,3.052,23620.0,NaN,199.880,NaN,NaN,14.999,1013.241,0.001,0.012
9,0.09,0.112000,3.678,23610.0,NaN,199.871,NaN,NaN,14.999,1013.237,0.001,0.014
10,0.10,0.151000,4.307,23600.0,NaN,199.862,NaN,NaN,14.999,1013.232,0.001,0.016
11,0.11,0.195000,4.940,23590.0,NaN,199.854,NaN,NaN,14.999,1013.227,0.001,0.017
12,0.12,0.245000,5.575,23580.0,NaN,199.845,NaN,NaN,14.998,1013.221,0.001,0.019
13,0.13,0.302000,6.214,23570.0,NaN,199.836,NaN,NaN,14.998,1013.215,0.001,0.021
14,0.14,0.365000,6.856,23560.0,NaN,199.827,NaN,NaN,14.998,1013.207,0.001,0.022
15,0.15,0.434000,7.502,23550.0,NaN,199.819,NaN,NaN,14.997,1013.199,0.001,0.024
16,0.16,0.509000,8.150,23540.0,NaN,199.810,NaN,NaN,14.997,1013.190,0.001,0.026
17,0.17,0.591000,8.802,23530.0,NaN,199.801,NaN,NaN,14.996,1013.181,0.001,0.028
18,0.18,0.678000,9.457,23510.0,NaN,199.792,NaN,NaN,14.996,1013.170,0.001,0.030
19,0.19,0.773000,10.115,23500.0,NaN,199.784,NaN,NaN,14.995,1013.159,0.001,0.032

In [9]:
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 3375 entries, 0 to 3374
Data columns (total 12 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Temps (s)                         3375 non-null   float64
 1   Altitude (m)                      3375 non-null   float64
 2   Vitesse totale (m/s)              3375 non-null   float64
 3   Masse (g)                         3375 non-null   float64
 4   Emplacement du CP (cm)            3354 non-null   float64
 5   Emplacement du CG (cm)            3375 non-null   float64
 6   Calibres marge de stabilité (​)   3354 non-null   float64
 7   Coefficient de force normale (​)  531 non-null    float64
 8   Température de l'air (°C)         3375 non-null   float64
 9   Pression atmosphérique (mbar)     3375 non-null   float64
 10  Air density (g/cm³)               3375 non-null   float64
 11  Mach number (​)                   3375 non-null   float64
dtypes: float64(12)
memory usage: 316.5 KB

In [12]:
df_clean.isna().sum()

Temps (s)                              0
Altitude (m)                           0
Vitesse totale (m/s)                   0
Masse (g)                              0
Emplacement du CP (cm)                21
Emplacement du CG (cm)                 0
Calibres marge de stabilité (​)       21
Coefficient de force normale (​)    2844
Température de l'air (°C)              0
Pression atmosphérique (mbar)          0
Air density (g/cm³)                    0
Mach number (​)                        0
dtype: int64

In [13]:
import pandas as pd

from app.services.csv_reader import read_openrocket_csv
from app.services.data_extractor import extract_useful_columns
from app.services.data_normalizer import normalize_openrocket_data

fichier = "sample_data/open_rocket_data.csv"

df_raw = read_openrocket_csv(fichier)
df_useful = extract_useful_columns(df_raw)
df_clean = normalize_openrocket_data(df_useful)

print("\n===== TABLEAU AVANT (avec NaN) =====")
df_clean

===== TABLEAU AVANT (avec NaN) =====

,Temps (s),Altitude (m),Vitesse totale (m/s),Masse (g),Emplacement du CP (cm),Emplacement du CG (cm),Calibres marge de stabilité (​),Coefficient de force normale (​),Température de l'air (°C),Pression atmosphérique (mbar),Air density (g/cm³),Mach number (​)
0,0.000,0.000000,0.000,23670.0,NaN,199.924,NaN,NaN,15.000,1013.250,0.001,0.007
1,0.010,0.000000,0.010,23670.0,NaN,199.921,NaN,NaN,15.000,1013.250,0.001,0.007
2,0.020,0.000523,0.136,23660.0,NaN,199.917,NaN,NaN,15.000,1013.250,0.001,0.007
3,0.030,0.003000,0.407,23660.0,NaN,199.914,NaN,NaN,15.000,1013.250,0.001,0.007
4,0.040,0.009000,0.824,23660.0,NaN,199.911,NaN,NaN,15.000,1013.249,0.001,0.008
...,...,...,...,...,...,...,...,...,...,...,...,...
3367,783.888,5.981000,5.196,15090.0,0.0,188.788,-12.586,NaN,14.961,1012.549,0.001,0.014
3368,784.135,4.781000,5.221,15090.0,0.0,188.788,-12.586,NaN,14.969,1012.689,0.001,0.014
3369,784.383,3.582000,5.233,15090.0,0.0,188.788,-12.586,NaN,14.977,1012.830,0.001,0.014
3370,784.630,2.382000,5.261,15090.0,0.0,188.788,-12.586,NaN,14.985,1012.971,0.001,0.014
3371,785.122,0.000000,5.281,15090.0,0.0,188.788,-12.586,NaN,15.000,1013.250,0.001,0.014

In [14]:
df_json = df_clean.astype(object)
df_json = df_json.where(pd.notna(df_json), None)

print("\n===== TABLEAU APRÈS (avec None) =====")
df_json

===== TABLEAU APRÈS (avec None) =====

,Temps (s),Altitude (m),Vitesse totale (m/s),Masse (g),Emplacement du CP (cm),Emplacement du CG (cm),Calibres marge de stabilité (​),Coefficient de force normale (​),Température de l'air (°C),Pression atmosphérique (mbar),Air density (g/cm³),Mach number (​)
0,0.0,0.0,0.0,23670.0,None,199.924,None,None,15.0,1013.25,0.001,0.007
1,0.01,0.0,0.01,23670.0,None,199.921,None,None,15.0,1013.25,0.001,0.007
2,0.02,0.000523,0.136,23660.0,None,199.917,None,None,15.0,1013.25,0.001,0.007
3,0.03,0.003,0.407,23660.0,None,199.914,None,None,15.0,1013.25,0.001,0.007
4,0.04,0.009,0.824,23660.0,None,199.911,None,None,15.0,1013.249,0.001,0.008
...,...,...,...,...,...,...,...,...,...,...,...,...
3367,783.888,5.981,5.196,15090.0,0.0,188.788,-12.586,None,14.961,1012.549,0.001,0.014
3368,784.135,4.781,5.221,15090.0,0.0,188.788,-12.586,None,14.969,1012.689,0.001,0.014
3369,784.383,3.582,5.233,15090.0,0.0,188.788,-12.586,None,14.977,1012.83,0.001,0.014
3370,784.63,2.382,5.261,15090.0,0.0,188.788,-12.586,None,14.985,1012.971,0.001,0.014
3371,785.122,0.0,5.281,15090.0,0.0,188.788,-12.586,None,15.0,1013.25,0.001,0.014